- name: hosting web page
  hosts: all
  become: true
  tasks: 
    - name: installing nginx
      package: 
        name: 
          - nginx
          - unzip
        state: present

    - name: download template
      shell: wget https://www.free-css.com/assets/files/free-css-templates/download/page287/dicet-tv.zip

    - name: extract zip file
      unarchive: 
        src: /home/ubuntu/dicet-tv.zip
        dest: /home/ubuntu
        remote_src: yes

    - name: delete indexfile
      file: 
        path: /usr/share/nginx/html/index.html
        state: absent

    - name: moving css to apache home
      shell:  cp -r /home/ubuntu/html/* /usr/share/nginx/html/index.html