- name: Registering vars
  hosts: all
  tasks:
    - name: Registering vars playbook
      shell: uptime
      register: OUTPUT
    
    - name: print output
      debug:
        msg: "{{OUTPUT.stdout}}"

    - name: Registering pwd playbook
      shell: pwd
      register: OUTPUT1 

     - name: print output
      debug:
        msg: "{{OUTPUT1.stdout}}"
  

        