- name: Registering vars
  hosts: all
  tasks:
    - name: Registering vars playbook
      shell: uptime
      register: OUTPUT
    
    - name: print output
      debug:
        msg: "{{OUTPUT.stdout}}"




        