- name: tomcat hosting
  hosts: all
  become: true
  tasks: 
    - name: java installing
      package: 
        name: default-jdk
        state: present

    - name: download tomcat
      get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz
        dest: /home/ubuntu

    - name: extracting file 
      unarchive: 
        src:  /home/ubuntu/apache-tomcat-9.0.71.tar.gz
        dest: /opt
        remote_src: yes

    - name: startup catelina
      shell: nohup /opt/apache-tomcat-9.0.71/bin/startup.sh         